# Generated by Django 4.2 on 2025-04-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('1', 'Nutricionista'), ('2', 'Ortopedista'), ('3', 'Dentista'), ('4', 'Pediatra'), ('5', 'Cardiologista'), ('6', 'Oftalmologista')], max_length=50)),
                ('crm', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('paciente', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'Agendado'), ('2', 'Realizado'), ('3', 'Cancelado')], max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
